mybatis/spring

pom.xml

I've updated spring version. Please review this.

Update Spring 4.2.5.RELEASE

---

src/main/java/org/mybatis/spring/SqlSessionFactoryBean.java
src/test/java/org/mybatis/spring/SqlSessionFactoryBeanTest.java

I've fixed to configure a `Configuration` instance  without config file(`mybatis-config.xml`) in `SqlSessionFactoryBean`.
In this changes, we can be configure `Configuration` easily using ["Type-safe Configuration Properties" of Spring Boot](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-typesafe-configuration-properties) or XML/Java Config based bean definition.
e.g.)
```java
@ConfigurationProperties(prefix = "mybatis.configuration")
@Bean
public Configuration mybatisConfiguration() {
return new Configuration();
}
```
What do you think ?

Allow direct configuration without config file at SqlSessionFactoryBean

---

src/site/es/xdoc/factorybean.xml
src/site/ja/xdoc/factorybean.xml
src/site/ko/xdoc/factorybean.xml
src/site/xdoc/factorybean.xml
src/site/zh/xdoc/factorybean.xml

I've added description for configuration of SqlSessionFactoryBean in document.
For details, refer to #108 .

Add description for configuration of SqlSessionFactoryBean #108

---

src/main/java/org/mybatis/spring/batch/MyBatisBatchItemWriter.java
src/main/java/org/mybatis/spring/batch/MyBatisCursorItemReader.java
src/main/java/org/mybatis/spring/batch/MyBatisPagingItemReader.java

I've fixed wrong javadoc.
Please review.

Fix wrong javadoc

---

src/main/java/org/mybatis/spring/batch/MyBatisCursorItemReader.java

Update license header on MyBatisCursorItemReader

---

pom.xml

Please review.
Note that the atomikos cannot update because tests failed.

Update ognl 3.1.4 and byteman-bmunit 3.0.5

---

pom.xml

Upgrade to Spring 4.2.6

---

pom.xml

* Atomikos 4.0.3
* Byteman Bmunit 3.0.6
* HSQLDB 2.3.4
Please merge.

Update dependency library version for test scope

---

src/site/ko/xdoc/index.xml

- Mybatis-spring requires version added : 1.3.0
- svn -> git

Update index.xml for ko

---

pom.xml

I've updated to Spring latest version.
Please review.

Upgrade to Spring 4.3.1.RELEASE

---

pom.xml

Upgrade to Spring 4.3.2.RELEASE

---

pom.xml

Upgrade to Spring 4.3.3.RELEASE

---

src/main/java/org/mybatis/spring/SqlSessionFactoryBean.java
src/test/java/org/mybatis/spring/SqlSessionFactoryBeanTest.java

I've add defensive code for nullable field.
Please review.

Add null-check for configurationProperty on SqlSessionFactoryBean

---

pom.xml

[OGNL 3.1.11](https://github.com/jkuhnert/ognl#release-notes---version-3111) has been released.

Update to OGNL 3.1.11

---

src/test/java/org/mybatis/spring/SqlSessionFactoryBeanTest.java

Add test for configurationProperties on SqlSessionFactoryBean

---

src/main/java/org/mybatis/spring/SqlSessionFactoryBean.java

I've fixed the enclosing character.

Polishing debug log message in SqlSessionFactoryBean

---

src/test/java/org/mybatis/spring/SqlSessionFactoryBeanTest.java
src/test/java/org/mybatis/spring/SqlSessionTemplateTest.java
src/test/java/org/mybatis/spring/annotation/MapperScanTest.java
src/test/java/org/mybatis/spring/batch/SpringBatchTest.java
src/test/java/org/mybatis/spring/config/NamespaceTest.java
src/test/java/org/mybatis/spring/mapper/MapperFactoryBeanTest.java
src/test/java/org/mybatis/spring/mapper/MapperScannerConfigurerTest.java
src/test/java/org/mybatis/spring/sample/AbstractSampleTest.java
src/test/java/org/mybatis/spring/sample/SampleConfigurationTest.java
src/test/java/org/mybatis/spring/submitted/autowire/AutowireTest.java
src/test/java/org/mybatis/spring/submitted/webapp_placeholder/WebappPlaceholderTest.java
src/test/java/org/mybatis/spring/submitted/xa/UserServiceTest.java
src/test/java/org/mybatis/spring/support/SqlSessionDaoSupportTest.java
src/test/java/org/mybatis/spring/transaction/SpringTransactionManagerTest.java

public modifier does not need on test method since JUnit 5.

Remove public modifier at @Test method

---

.travis.yml
pom.xml

Support JDK9 on Travis CI

---

src/site/zh/xdoc/index.xml

I translated some words in index.xml into Chinese, and I hoped to translate this document for a long time in my spare time.

modify zh index 2017/11/08

---

src/site/zh/xdoc/factorybean.xml
src/site/zh/xdoc/getting-started.xml.vm
src/site/zh/xdoc/index.xml

I have added some new translate which is not be translated before.

impove some zh translate 2017/11/22

---

src/site/es/xdoc/sample.xml
src/site/ja/xdoc/sample.xml
src/site/xdoc/sample.xml

misleading sentence modified.

---

pom.xml

Upgrade to mybatis-parent 31-SNAPSHOT

---

.travis.yml

Support JDK10 on Travis CI

---

src/main/java/org/mybatis/spring/batch/MyBatisBatchItemWriter.java
src/main/java/org/mybatis/spring/batch/builder/MyBatisBatchItemWriterBuilder.java
src/test/java/org/mybatis/spring/batch/MyBatisBatchItemWriterTest.java
src/test/java/org/mybatis/spring/batch/builder/MyBatisBatchItemWriterBuilderTest.java

Fixes gh-21
@mybatis/committers 
what do you think about my idea?
Please review this.
Thanks.

Support converting item to parameter object

---

.mvn/wrapper/maven-wrapper.properties
.travis.yml
pom.xml

Fix the ssl protocol_version error #311

---

src/main/java/org/mybatis/spring/config/mybatis-spring.xsd

Using  to let ide recognize the attribute is kind of , so ide can provide more information for this attribute.
Affected attribute:
- factory-ref
- template-ref
Apply gh-284 to master branch

Optimize xsd for ide hints.

---

src/main/java/org/mybatis/spring/SqlSessionFactoryBean.java
src/test/java/org/mybatis/spring/SqlSessionFactoryBeanTest.java

Support to configure LanguageDriver via SqlSessionFactoryBean

---

.travis.yml
pom.xml

Support openjdk13 on Travis CI

---

.travis.yml

Support openjdk-ea on Travis CI

---

pom.xml
src/test/java/org/mybatis/spring/submitted/xa/applicationContext.xml

Bump transactions-jdbc from 4.0.6 to 5.0.3

---

.travis.yml

Change version to spring 5.1.x and spring-batch 4.1.x on Travis CI

---

src/main/java/org/mybatis/spring/mapper/MapperScannerConfigurer.java

The updatePropertyValue method just gets the property value

Change the method name to getPropertyValue

---

pom.xml
src/main/java/org/mybatis/spring/MyBatisExceptionTranslator.java

Fixes gh-540
* Change version at pom.xml
* throw `UncategorizedSQLException` if return null on `SQLExceptionTranslator` (for keep same behavior with Spring 5.2 or before)

Support Spring 5.3

---

.travis.yml

Support CI with spring 5.2 and spring-batch 4.2

---

src/site/es/markdown/sample.md
src/site/ja/markdown/sample.md
src/site/ko/markdown/sample.md
src/site/markdown/mappers.md
src/site/markdown/sample.md
src/site/zh/markdown/sample.md

fix bad link and typos

---

src/site/ja/markdown/factorybean.md

Fix typo in Japanese translation

---

.github/workflows/compatibility-check-spring6.yaml

Add the new GitHub workflow for checking compatibility with Spring 6 and Spring Batch 5

---

src/main/java/org/mybatis/spring/annotation/MapperScannerRegistrar.java
src/main/java/org/mybatis/spring/config/MapperScannerBeanDefinitionParser.java
src/main/java/org/mybatis/spring/mapper/ClassPathMapperScanner.java
src/test/java/org/mybatis/spring/annotation/MapperScanTest.java
src/test/java/org/mybatis/spring/config/NamespaceTest.java
src/test/java/org/mybatis/spring/mapper/MapperScannerConfigurerTest.java

* Set infrastructure role for MapperScannerConfigurer bean
* Set the mapperInterface to MapperFactoryBean for accessing the interface type at bean definition post processing
See gh-635

Change to support spring-native

---

pom.xml
src/test/java/org/mybatis/spring/SqlSessionFactoryBeanTest.java

Bump mybatis from 3.5.9 to 3.5.10

---

src/main/java/org/mybatis/spring/SqlSessionTemplate.java

"that" is repeat

---

src/main/java/org/mybatis/spring/batch/MyBatisPagingItemReader.java
src/test/java/org/mybatis/spring/sample/SampleJobJavaConfigTest.java
src/test/java/org/mybatis/spring/sample/SampleJobXmlConfigTest.java

Remove doJumpToPage method on MyBatisPagingItemReader

---

pom.xml

Compile with -parameters option

---

pom.xml

Change to use maven.compiler.parameters

---

pom.xml

Apply Spring 6 and Spring Batch 5 official release version

---

pom.xml

Update to spring-framework 6.0.2

---

src/main/java/org/mybatis/spring/mapper/ClassPathMapperScanner.java

MapperScannerConfigurer#includeAnnotationConfig set to false in native image

---

pom.xml

(cherry picked from commit c9148ceae772796f52c74d620a8a56bfdaeacd60)

Update dependency org.slf4j:slf4j-simple to v2.0.5

---

.github/workflows/ci.yaml
.mvn/extensions.xml
.mvn/settings.xml
.mvn/wrapper/MavenWrapperDownloader.java
pom.xml
src/test/java/org/mybatis/spring/MyBatisSpringTest.java
src/test/java/org/mybatis/spring/sample/SampleSqlSessionTest.java
src/test/java/org/mybatis/spring/submitted/xa/UserServiceTest.java
src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

cannot get to 4.10 or better still.  Some minor adjustments to mock maker here, updated maven wrapper piece missed by the bot.  Basically keeping this for history purposes of attempts to see if anyone else had any luck.

Attempting to solve mockito issues

---

src/main/java/org/mybatis/spring/annotation/MapperScan.java
src/main/java/org/mybatis/spring/annotation/MapperScannerRegistrar.java
src/main/java/org/mybatis/spring/config/MapperScannerBeanDefinitionParser.java
src/main/resources/org/mybatis/spring/config/mybatis-spring.xsd
src/test/java/org/mybatis/spring/annotation/MapperScanTest.java
src/test/java/org/mybatis/spring/annotation/MyBean.java
src/test/java/org/mybatis/spring/annotation/override.properties
src/test/java/org/mybatis/spring/annotation/placeholders.properties
src/test/java/org/mybatis/spring/config/MyBean.java
src/test/java/org/mybatis/spring/config/MyFactoryBean.java
src/test/java/org/mybatis/spring/config/NamespaceTest.java
src/test/java/org/mybatis/spring/config/override.properties
src/test/java/org/mybatis/spring/config/placeholders.properties
src/test/java/org/mybatis/spring/config/process-property-placeholders-false.xml
src/test/java/org/mybatis/spring/config/process-property-placeholders-true.xml

Support processPropertyPlaceHolders option in mapper:scan and @MapperScan

---

pom.xml

(cherry picked from commit 08004f22009a409b23415dd485dc5c2ba7a0fbac)

Update dependency org.mybatis:mybatis to v3.5.14

---

src/site/zh_CN/markdown/index.md

change zh to zh_cn in zh_cn/markdown/index.md

fix i18n link error in site.

---

src/test/resources/org/mybatis/spring/sample/config/applicationContext-job.xml

Use the TaskExecutorJobLauncher instead of SimpleJobLauncher
