mybatis/spring

- pom.xml
- src/main/java/org/mybatis/spring/SqlSessionTemplate.java
- src/main/java/org/mybatis/spring/batch/MyBatisCursorItemReader.java
- src/test/java/org/mybatis/spring/batch/SpringBatchTest.java
- src/test/java/org/mybatis/spring/batch/applicationContext.xml
- src/test/java/org/mybatis/spring/batch/dao/EmployeeMapper.xml
- src/test/java/org/mybatis/spring/batch/db/database-schema.sql
- src/test/java/org/mybatis/spring/batch/db/database-test-data.sql
- src/test/java/org/mybatis/spring/batch/domain/Employee.java
Hi all,
This PR adds a MyBatisCursorItemReader that leverage Cursor feature proposed by mybatis/mybatis-3#437.
It replace the previous PR mybatis/mybatis-spring#8.
The version is bumped to 1.3.0 since it now depends on mybatis 3.4.0
Unlike MyBatisPagingItemReader, it allows a correct fetch of statements with nested resultmaps. Also, it’s much more efficient since it does only one statement execution at the beginning and keeps the same cursor open until the end.
Usage samples can be found in SpringBatchTest unit test.
Best regards,
Guillaume
> MyBatisCursorItemReader

- src/main/java/org/mybatis/spring/SqlSessionTemplate.java
#77 : SqlSessionTemplate bean is not valid for disposal by Spring container
https://github.com/mybatis/spring/issues/77
> SqlSessionTemplate bean is not valid for disposal by Spring container (https://github.com/mybatis/spring/issues/77)

- src/main/java/org/mybatis/spring/SqlSessionFactoryBean.java
when parse mapper xml files , it needs to know what databaseId is。
org.apache.ibatis.builder.xml.XMLConfigBuilder'smethod:databaseIdProviderElement,will set databaseId if "environment != null && databaseIdProvider != null",but the configuration's environment  is null becase it will be seted after  "xmlConfigBuilder.parse();" in file "SqlSessionFactoryBean.java"
> fix #64 set databaseId before parse mapper xmls

- src/main/java/org/mybatis/spring/SqlSessionFactoryBean.java
- src/test/java/org/mybatis/spring/SqlSessionFactoryBeanTest.java
- src/test/java/org/mybatis/spring/mybatis-config.xml
> Add vfsImpl property in SqlSessionFactoryBean

- src/main/java/org/mybatis/spring/SqlSessionFactoryBean.java
I've fixed #119 .
Please review.
> Modify to use a custom VFS when scanning type aliases on SqlSessionFactoryBean

- pom.xml
Please review.
**Note:**
An atomikos transaction log file(such as `tmlog0.log`) on root directory is unnecessary by this change.
Please MyBatis developer remove its file on local machine.
And In this change, transaction log file will output to the build directory(`./target`).
> Upgrade to Atomikos 4.0.2

- pom.xml
- src/main/java/org/mybatis/spring/mapper/MapperScannerConfigurer.java
@harawata 
I've polished to use `ConfigurableApplicationContext`(interface) instead of `AbstractApplicationContext`(abstract class).
I think it should be independent on the specific class or abstract class.
What do you think ?
#144
> Polish to use ConfigurableApplicationContext instead of AbstractApplicationContext #144

- pom.xml
Atomikos 4.0.4+ is required Java 7+.
> Add comment about atomikos version limitation

- src/test/java/org/mybatis/spring/annotation/MapperScanTest.java
- src/test/java/org/mybatis/spring/config/NamespaceTest.java
- src/test/java/org/mybatis/spring/mapper/MapperScannerConfigurerTest.java
In the current implementation, if an assertion is failing, `ApplicationContext` does not close.
> Fix to close the ApplicationContext at assertion failing

- src/main/java/org/mybatis/spring/annotation/MapperScan.java
- src/main/java/org/mybatis/spring/annotation/MapperScannerRegistrar.java
- src/main/java/org/mybatis/spring/annotation/MapperScans.java
- src/test/java/org/mybatis/spring/annotation/MapperScanTest.java
- src/test/java/org/mybatis/spring/annotation/mapper/ds1/Ds1Mapper.java
- src/test/java/org/mybatis/spring/annotation/mapper/ds2/Ds2Mapper.java
I will propose to allow a repeatable annotation supported by Java 8 on `@MapperScan` like `@ComponentScan` provided by Spring Framework.
What do you think?
> Allow repeatable for @MapperScan

- src/main/java/org/mybatis/spring/batch/builder/MyBatisBatchItemWriterBuilder.java
- src/main/java/org/mybatis/spring/batch/builder/MyBatisCursorItemReaderBuilder.java
- src/main/java/org/mybatis/spring/batch/builder/MyBatisPagingItemReaderBuilder.java
- src/main/java/org/mybatis/spring/batch/builder/package-info.java
- src/test/java/org/mybatis/spring/batch/builder/MyBatisBatchItemWriterBuilderTest.java
- src/test/java/org/mybatis/spring/batch/builder/MyBatisCursorItemReaderBuilderTest.java
- src/test/java/org/mybatis/spring/batch/builder/MyBatisPagingItemReaderBuilderTest.java
I will propose to add builder classes for `ItemReader` and `ItemWriter` provided by MyBatis because Spring Batch 4.0 will support builder classes.
About builder class, please see [here](https://docs.spring.io/spring-batch/4.0.x/reference/html/whatsnew.html#whatsNewBuilders)
What do you think?
> Add builder classes for ItemReader and ItemWriter

- src/test/java/org/mybatis/spring/batch/MyBatisCursorItemReaderTest.java
This PR adds a missing assertion in `MyBatisCursorItemReaderTest.testCloseOnFailing()`.
> Add a missing assertion in MyBatisCursorItemReaderTest.testCloseOnFailing()

- src/site/es/xdoc/batch.xml
- src/site/ja/xdoc/batch.xml
- src/site/ko/xdoc/batch.xml
- src/site/ko/xdoc/boot.xml
- src/site/ko/xdoc/factorybean.xml
- src/site/ko/xdoc/getting-started.xml.vm
- src/site/ko/xdoc/index.xml
- src/site/ko/xdoc/mappers.xml
- src/site/ko/xdoc/sample.xml
- src/site/ko/xdoc/sqlsession.xml
- src/site/ko/xdoc/transactions.xml
- src/site/ko/xdoc/using-api.xml
- src/site/site_ko.xml
- src/site/xdoc/batch.xml
- src/site/zh/xdoc/batch.xml
- korean documentaion translated.
- __IteamReader__ typo corrected
> Korean translation updated

- src/main/java/org/mybatis/spring/annotation/MapperScannerRegistrar.java
- src/main/java/org/mybatis/spring/mapper/ClassPathMapperScanner.java
In this change, I've added the `ClassPathMapperScanner#setMapperFactoryBeanClass`. It use instead  of the `ClassPathMapperScanner#setMapperFactoryBean` (change to deprecated API).
> Prevent unnecessary generating instance of MapperFactoryBean

- src/main/java/org/mybatis/spring/config/MapperScannerBeanDefinitionParser.java
- src/main/java/org/mybatis/spring/config/mybatis-spring.xsd
- src/main/java/org/mybatis/spring/mapper/MapperScannerConfigurer.java
- src/test/java/org/mybatis/spring/annotation/MapperScanTest.java
- src/test/java/org/mybatis/spring/config/NamespaceTest.java
- src/test/java/org/mybatis/spring/config/mapper-factory-bean-class.xml
- src/test/java/org/mybatis/spring/mapper/MapperScannerConfigurerTest.java
- src/test/java/org/mybatis/spring/type/DummyMapperFactoryBean.java
I've supported to specify a custom MapperFactoryBean on `<mybatis:scan>`(`MapperScannerBeanDefinitionParser`) and `MapperScannerConfigurer` because support `factoryBean` attribute at `@MapperScan`.
`@MapperScan` (Already supported in 2.0.0 or before) :
```java
@MapperScan(basePackages = "x.y.z.mapper", factoryBean = CustomMapperFactoryBean.class)
public class DataAccessConfiguration {
// ...
}
```
XML namespace (Will support since 2.0.1):
```xml
<mybatis:scan base-package="x.y.z.mapper"
mapper-factory-bean-class="x.y.z.mapper.CustomMapperFactoryBean"/>
```
`MapperScannerConfigurer` (Will support since 2.0.1):
```xml
<bean class="org.mybatis.spring.mapper.MapperScannerConfigurer">
<property name="basePackage" value="x.y.z.mapper" />
<property name="mapperFactoryBeanClass" …
```
> Allow to specify custom MapperFactoryBean class on xml based bean definition

- src/main/java/org/mybatis/spring/config/mybatis-spring-1.2.xsd
Using `<tool:annotation kind="ref">` to let ide recognize the attribute is kind of `ref`, so ide can provide more information for this attribute.
Affected attribute:
- factory-ref
- template-ref
> Optimize xsd for ide hints

- src/main/java/org/mybatis/spring/batch/MyBatisPagingItemReader.java
This PR is linked to the issue #323 
Basically, I used the `SqlSession` interface instead of the `SqlSessionTemplate` implementation.
I override `doOpen()` and `doClose()` to avoid initialization of the connection through `afterPropertiesSet`.
This is not a final version ready to be merged since it is missing unit tests. I just wanted to show any other solution.
> Relax MyBatisPagingItemReader to allow constructor instanciation

- src/main/java/org/mybatis/spring/SqlSessionFactoryBean.java
- src/test/java/org/mybatis/spring/SqlSessionFactoryBeanTest.java
> Allow to specify a wildcard at typeAliasesPackage and typeHandlersPackage

- src/main/java/org/mybatis/spring/SqlSessionFactoryBean.java
- src/test/java/org/mybatis/spring/SqlSessionFactoryBeanTest.java
- src/test/java/org/mybatis/spring/scan/ScanAnnotation.java
- src/test/java/org/mybatis/spring/scan/ScanClass1.java
- src/test/java/org/mybatis/spring/scan/ScanClass2.java
- src/test/java/org/mybatis/spring/scan/ScanEnum.java
- src/test/java/org/mybatis/spring/scan/ScanInterface.java
- src/test/java/org/mybatis/spring/scan/package-info.java
- src/test/java/org/mybatis/spring/type/TypeHandlerFactory.java
- src/test/java/org/mybatis/spring/type/package-info.java
> Filter anonymous class and interface when package scan

- pom.xml
derby breaks the tests.  All others pass.
> Update dependencies (except derby)

- .editorconfig
See [here](https://editorconfig.org/) for usage.
> Add `.editorconfig` to maintain consistent coding styles

- src/main/java/org/mybatis/spring/annotation/MapperScan.java
- src/main/java/org/mybatis/spring/annotation/MapperScannerRegistrar.java
- src/main/java/org/mybatis/spring/config/MapperScannerBeanDefinitionParser.java
- src/main/java/org/mybatis/spring/mapper/ClassPathMapperScanner.java
- src/main/java/org/mybatis/spring/mapper/MapperScannerConfigurer.java
- src/main/resources/org/mybatis/spring/config/mybatis-spring.xsd
- src/test/java/org/mybatis/spring/annotation/MapperScanTest.java
- src/test/java/org/mybatis/spring/annotation/scan.properties
- src/test/java/org/mybatis/spring/config/NamespaceTest.java
- src/test/java/org/mybatis/spring/config/lazy.properties
- src/test/java/org/mybatis/spring/config/lazy.xml
- src/test/java/org/mybatis/spring/mapper/MapperScannerConfigurerTest.java
- src/test/java/org/mybatis/spring/submitted/webapp_placeholder/WebappPlaceholderTest.java
- src/test/java/org/mybatis/spring/submitted/webapp_placeholder/spring.xml
> Support enable/disable lazy Initialization on mapper scanning feature

- src/main/java/org/mybatis/spring/SqlSessionFactoryBean.java
- src/test/java/org/mybatis/spring/AbstractMyBatisSpringTest.java
- src/test/java/org/mybatis/spring/SqlSessionFactoryBeanTest.java
- src/test/java/org/mybatis/spring/mapper/MapperFactoryBeanTest.java
- src/test/java/org/mybatis/spring/sample/config/SampleConfig.java
Variable-length arguments work well with JavaConfig.
> Change to Variable-length argument from array argument on SqlSessionFactoryBean

- src/main/java/org/mybatis/spring/SqlSessionFactoryBean.java
- src/test/java/org/mybatis/core/jdk/type/AtomicNumberTypeHandler.java
- src/test/java/org/mybatis/spring/SqlSessionFactoryBeanTest.java
> Allow to scan TypeHandler that pass Class<?> to constructor

- src/main/java/org/mybatis/spring/batch/MyBatisBatchItemWriter.java
Modify comment in Line 67. As in code line 150, if assertUpdates is true, only results.size()==1 can pass the validation
#390
> Update comment in MyBatisBatchItemWriter.java

- src/main/java/org/mybatis/spring/MyBatisExceptionTranslator.java
> Allow to configure the SQLExceptionTranslator on MyBatisExceptionTranslator

- src/main/java/org/mybatis/spring/SqlSessionTemplate.java
- src/main/java/org/mybatis/spring/batch/MyBatisCursorItemReader.java
- src/main/java/org/mybatis/spring/transaction/SpringManagedTransaction.java
This reverts commit 5ca5f2df3577f8b670292cfb0864a57e9b8685e6.
Fixes gh-427.
> Revert "Remove unnecessary throws clause"

- src/main/java/org/mybatis/spring/annotation/MapperScan.java
- src/main/java/org/mybatis/spring/annotation/MapperScannerRegistrar.java
- src/site/es/xdoc/mappers.xml
- src/site/ja/xdoc/mappers.xml
- src/site/ko/xdoc/mappers.xml
- src/site/xdoc/mappers.xml
- src/site/zh/xdoc/mappers.xml
- src/test/java/org/mybatis/spring/annotation/MapperScanTest.java
- src/test/java/org/mybatis/spring/annotation/mapper/ds1/AppConfigWithDefaultMapperScanAndRepeat.java
- src/test/java/org/mybatis/spring/annotation/mapper/ds1/AppConfigWithDefaultMapperScans.java
- src/test/java/org/mybatis/spring/mapper/AppConfigWithDefaultPackageScan.java
When I am working on gradle multi project, I often use below config class to import sub modules.  `ComponentScan` uses declared class's package if the `basePackages` attribute is not present. However, `MapperScan` will not work like `ComponentScan`. I think this is obvious case and `MapperScan` should treat like `ComponentScan`
```
package a;
@Configuration
@ComponentScan
@MapperScan("a")
public class xx....
```
> Use declared class's package as base package if not present base packages on @MapperScan

- src/main/java/org/mybatis/spring/mapper/MapperScannerConfigurer.java
- src/test/java/org/mybatis/spring/annotation/MapperScanTest.java
- src/test/java/org/mybatis/spring/annotation/factory/SimpleFactoryBean.java
> Prevent bean eager initialization on MapperScannerConfigurer

- src/main/java/org/mybatis/spring/SqlSessionFactoryBean.java
- src/test/java/org/mybatis/spring/SqlSessionFactoryBeanTest.java
> Add new property for customizing the defaultEnumTypeHandler

- src/site/ko/xdoc/mappers.xml
I found a mistranslation in the Injecting Mappers page in Korean and corrected it. @fromm0
> correct a mistranslation translated in Korean.

- src/main/java/org/mybatis/spring/annotation/MapperScan.java
- src/main/java/org/mybatis/spring/annotation/MapperScannerRegistrar.java
- src/main/java/org/mybatis/spring/config/MapperScannerBeanDefinitionParser.java
- src/main/java/org/mybatis/spring/mapper/ClassPathMapperScanner.java
- src/main/java/org/mybatis/spring/mapper/MapperScannerConfigurer.java
- src/main/resources/org/mybatis/spring/config/mybatis-spring.xsd
- src/test/java/org/mybatis/spring/annotation/MapperScanTest.java
- src/test/java/org/mybatis/spring/annotation/mapper/ds1/Ds1Mapper.java
- src/test/java/org/mybatis/spring/annotation/mapper/ds2/Ds2Mapper.java
- src/test/java/org/mybatis/spring/config/NamespaceTest.java
- src/test/java/org/mybatis/spring/config/default-scope.properties
- src/test/java/org/mybatis/spring/config/default-scope.xml
- src/test/java/org/mybatis/spring/mapper/MapperScannerConfigurerTest.java
- src/test/java/org/mybatis/spring/mapper/ScopedProxyMapper.java
Fixes gh-476
By this change, the develop become can specified scope of mapper using mapper scan feature option and scope annotation(`@Scope`, `@RefreshScope`, etc ...).
The `defaultScope` apply to the mapper bean(`MapperFactoryBean`) when scope of scanned bean definition is `singleton` (default scope) and create a scoped proxy bean for scanned mapper when final scope is not `singleton`.
The developer can specify the scope of mapper bean that not specified scope annotation using option of mapper scan feature. 
```java
@Cpnfiguration
@MapperScan(defaultScope = "refresh")
class MyBatisConfig {
// ...
}
```
```java
@Bean
MapperScannerConfigurer mapperScannerConfigurer() {
MapperScannerConfigurer configurer = new MapperScannerConfigurer();
configurer.setDefaultScope("refresh");
// ...
return …
```
> Support scoped proxy on mapper scan feature

- src/main/java/org/mybatis/spring/mapper/ClassPathMapperScanner.java
- src/test/java/org/mybatis/spring/mapper/MapperScannerConfigurerTest.java
https://github.com/mybatis/spring-boot-starter/issues/475
https://github.com/spring-projects/spring-boot/commit/f4985abf3cd299f0842d9f474942c418f177eb13
I found the solution in a similar bug report.
https://github.com/spring-projects/spring-boot/issues/21379
As the constant was added in Spring Beans 5.2, I had to declare a package private constant.
> Set attribute that helps MockitoPostProcessor replace a MyBatis mapper bean with a mock

- .github/workflows/ci.yaml
- .github/workflows/coveralls.yaml
- .github/workflows/support.yaml
See gh-634
At first, I modify standard CI setting for ignoring on `compatibility-check-spring6` branch. At next, I add branch to check a compatibility with Spring 6 and Spring Batch 5. At last, I add new GitHub workflow to check a compatibility with Spring 6 and Spring Batch 5.
> Modify standard CI setting for ignoring on compatibility-check-spring6 branch

- pom.xml
instead of inheriting timestamp from parent, which represents the timestamp when the parent was released, having a local timestamp will be more accurate to the actual release
> local output timestamp for Reproducible Builds

- src/main/java/org/mybatis/spring/SqlSessionFactoryBean.java
NestedIOException was removed from Spring Framework with https://github.com/spring-projects/spring-framework/commit/2fb1dd177b7b056f30a9de0739d8afdef37d72aa
> Remove usage of NestedIOException.

- src/main/java/org/mybatis/spring/annotation/MapperScan.java
- src/main/java/org/mybatis/spring/annotation/MapperScannerRegistrar.java
Introduce Spring's `AliasFor` declaration in `MapperScan`,  We only need to get all the attributes  through `basePackages` , without checking `value`, even if the user only fills in `value`.
Also this annotation `AliasFor` adds readability to some extent, I think this is a nice feature and hope you can consider introducing, looking forward to your reply.
> Introduce Spring's AliasFor declaration in MapperScan

- src/main/java/org/mybatis/spring/batch/MyBatisCursorItemReader.java
- src/main/java/org/mybatis/spring/batch/MyBatisPagingItemReader.java
- src/main/java/org/mybatis/spring/batch/builder/MyBatisCursorItemReaderBuilder.java
- src/main/java/org/mybatis/spring/batch/builder/MyBatisPagingItemReaderBuilder.java
- src/test/java/org/mybatis/spring/batch/builder/MyBatisCursorItemReaderBuilderTest.java
- src/test/java/org/mybatis/spring/batch/builder/MyBatisPagingItemReaderBuilderTest.java
In my use case of  ```MyBatisCursorItemReader```  like below, I have to specify query parameters **before** the Spring Container is initialized, which works well at first.
```java
@Configuration
public class SomeStepConfig {
...
@Bean
public Step someStep() {
return stepBuilderFactory.get("someStep")
.<SomeIn, SomeOut>chunk(1000)
.reader(reader())
.processor(processor())
.writer(writer())
.build();
}
MyBatisCursorItemReader reader() {
return new MyBatisCursorItemReaderBuilder<SomeIn>()
.sqlSessionFactory(this.sqlSessionFactory)
.queryId("selectSelectId")
.parameterValues(Collections.singletonMap("key", "value"))
.build();
}
...
}
```
After a few iterations, the query parameters needs to be determined by a preceding step, which is **after** Spring Container initialized, and I didn't come …
> Add parameter supplier support to spring batch readers

- src/main/java/org/mybatis/spring/mapper/ClassPathMapperScanner.java
> Add a new option whether print warning log if not found mappers that matches conditions on ClassPathMapperScanner

- pom.xml
fixes #759
this is the filtering strategy that uses explicit maven-resources-plugin execution (bound to site lifecycle) instead of hijacking main resources
> filter site content without hijacking main resources

- src/main/java/org/mybatis/spring/SqlSessionFactoryBean.java
fixes #796 
1. From the implementation of SqlSessionFactory, I think that it does not need to listen to all ApplicationEvents, and only needs to listen to ContextRefreshedEvent.
2. When there are multiple ApplicationContexts in Spring, ContextClosedEvent may be broadcasted multiple times. For example, FeignContext, since SqlSessionFactory listens to all ApplicationEvents, if the application is closed, when SqlSessionFactoryBean is destroyed first, and FeignContext is destroyed later, ContextClosedEvent will be broadcasted. When Spring tries to get the listener, BeanCreationNotAllowedException is thrown because SqlSessionFactoryBean's singleton bean has been destroyed and it indicates that singletons are currently being destroyed (singletonsCurrentlyInDestruction=true).
Although Spring …
> fix: change the event type that SqlSessionFactory is listening to

- src/main/java/org/mybatis/spring/SqlSessionFactoryBean.java
- src/test/java/org/mybatis/spring/SqlSessionFactoryBeanTest.java
- src/test/java/org/mybatis/spring/TestMapper2.xml
- src/test/java/org/mybatis/spring/TestMapper3.xml
Fixes gh-787
* addMapperLocations
* addTypeHandlers
* addScriptingLanguageDrivers
* addPlugins
* addTypeAliases
> Support appendable method on SqlSessionFactoryBean

- src/main/java/org/mybatis/spring/SqlSessionFactoryBean.java
- src/test/java/org/mybatis/spring/SqlSessionFactoryBeanTest.java
- src/test/java/org/mybatis/spring/TestMapper2.xml
- src/test/java/org/mybatis/spring/TestMapper3.xml
> Support appendable method on SqlSessionFactoryBean on 2.1.x

- src/main/java/org/mybatis/spring/mapper/ClassPathMapperScanner.java
Fixes gh-780
Fix to use the AotDetector#useGeneratedArtifacts() instead of NativeDetector.inNativeImage() for set the includeAnnotationConfig to false on the ClassPathMapperScanner
> Support spring.aot.enabled=true

- src/main/java/org/mybatis/spring/SqlSessionUtils.java
TransactionSynchronizationAdapter is deprecated already
> Use the TransactionSynchronization instead of TransactionSynchronizationAdapter

- src/main/java/org/mybatis/spring/annotation/MapperScan.java
- src/main/java/org/mybatis/spring/annotation/MapperScannerRegistrar.java
- src/main/java/org/mybatis/spring/config/MapperScannerBeanDefinitionParser.java
- src/main/resources/org/mybatis/spring/config/mybatis-spring.xsd
- src/test/java/org/mybatis/spring/annotation/MapperScanTest.java
- src/test/java/org/mybatis/spring/annotation/MyBean.java
- src/test/java/org/mybatis/spring/annotation/override.properties
- src/test/java/org/mybatis/spring/annotation/placeholders.properties
- src/test/java/org/mybatis/spring/config/MyBean.java
- src/test/java/org/mybatis/spring/config/MyFactoryBean.java
- src/test/java/org/mybatis/spring/config/NamespaceTest.java
- src/test/java/org/mybatis/spring/config/override.properties
- src/test/java/org/mybatis/spring/config/placeholders.properties
- src/test/java/org/mybatis/spring/config/process-property-placeholders-false.xml
- src/test/java/org/mybatis/spring/config/process-property-placeholders-true.xml
> Support processPropertyPlaceHolders option in mapper:scan and @MapperScan on 2.1.x

- .github/workflows/ci.yaml
- pom.xml
> Support JDK 22 on CI

- .github/workflows/ci.yaml
> Switch to temurin as JDK distribution on CI for support JDK 22

- src/main/java/org/mybatis/spring/MyBatisExceptionTranslator.java
- src/main/java/org/mybatis/spring/MyBatisSystemException.java
- src/test/java/org/mybatis/spring/MyBatisExceptionTranslatorTest.java
Since Spring 6, `org.springframework.core.NestedRuntimeException` no longer includes the message of the wrapped exception.
https://github.com/spring-projects/spring-framework/issues/25162
Should fix gh-887
> Adjust MyBatisSystemException to Spring 6

- pom.xml
- src/main/java/org/mybatis/spring/mapper/ClassPathMapperScanner.java
- src/main/java/org/mybatis/spring/mapper/MapperScannerConfigurer.java
- src/test/java/org/mybatis/spring/mapper/AnnotatedMapperOnPropertyCondition.java
- src/test/java/org/mybatis/spring/mapper/MapperScannerConfigurerTest.java
In current implementation, the `Environment` is not added to `ClassPathMapperScanner`. So the scanner can not get any property from the application environment when registering bean defination.
```java
@Mapper
@ConditionalOnProperty(prefix = "mapper", value = "condition", havingValue = "true")
public interface AnnotatedMapperOnPropertyCondition {
void method();
}
```
> Add environment to ClassPathMapperScanner to get properties from PropertySources

- src/main/java/org/mybatis/spring/MyBatisExceptionTranslator.java
> Replace synchronized method with Lock
